name: "Validate PR with Docker Model Runner"
on:
  pull_request:
    branches:
      - main

jobs:
  ai-pr-check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Block calls to segment.io
        shell: bash
        run: |
          grep -qxF '127.0.0.2 api.segment.io' /etc/hosts || echo '127.0.0.2 api.segment.io' | sudo tee -a /etc/hosts

      - name: Install macOS Docker Desktop dmg
        shell: bash
        run: |
          sw_vers
          mkdir ./temp
          mkdir ./mount

          buildUrl="https://desktop-stage.docker.com/mac/main/arm64/186043/Docker.dmg"

          sudo mkdir -p /Library/PrivilegedHelperTools
          echo "Downloading Docker Desktop..."
          curl --fail -o ./temp/DockerDesktop.dmg $buildUrl
          echo "Mounting Docker Desktop DMG..."
          /usr/bin/hdiutil attach -noverify ./temp/DockerDesktop.dmg -mountpoint ./mount/desktop -nobrowse
          echo "dmg mounted"
          echo "Installing Docker Desktop..."
          sudo ./mount/desktop/Docker.app/Contents/MacOS/install --accept-license --user runner
          echo "dmg installed"

          echo "ls /Library/Application Support/com.docker.docker"
          ls "/Library/Application Support/com.docker.docker" || true
          mkdir -p ./cache/desktopInstallSettings
          cp "/Library/Application Support/com.docker.docker/"* ./cache/desktopInstallSettings/
          echo "ls ./cache/desktopInstallSettings/"
          ls ./cache/desktopInstallSettings/ || true

          echo "Unmounting DMG..."
          /usr/bin/hdiutil detach ./mount/desktop
          echo "dmg unmounted"

      - name: Install macOS Docker Desktop app
        shell: bash
        run: |
          echo "Starting Docker Desktop in unattended mode..."
          /usr/bin/open /Applications/Docker.app --args --unattended --telemetry
          echo "Waiting 120 seconds for Docker Desktop to start..."
          sleep 120
          echo "Checking Docker processes after startup..."
          ps aux | grep -i docker
          echo "Verifying Docker socket status..."
          ls -la /var/run/docker.sock || echo "Docker socket not found!"
          echo "Displaying recent Docker logs..."
          log show --predicate 'process contains "Docker"' --last 2m || echo "No Docker logs found!"

      - name: Wait for Docker to be up and running
        shell: bash
        run: |
          tries=0
          until docker ps || [ $tries -ge 20 ]; do
            echo "Docker daemon not yet ready, retrying in 10 seconds..."
            sleep 10
            tries=$((tries+1))
            if [ $tries -eq 12 ]; then
              echo "Docker daemon did not start in time."
              exit 1
            fi
          done
          echo "Docker started and ready."
          docker version

      - name: Pull AI Model
        shell: bash
        run: |
          docker model pull ignaciolopezluna020/llama3.2-1b

      - name: Validate PR Description
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        shell: bash
        run: |
          docker model run ignaciolopezluna020/llama3.2-1b "Review this PR description for clarity and completeness based on these guidelines:
          1. Clearly state the change implemented.
          2. Include issue numbers if relevant.
          3. Explicitly state any breaking changes.

          PR Description:
          \"$PR_DESCRIPTION\""
