name: "Validate PR with Docker Model Runner"
on:
  pull_request:
    branches:
      - main

jobs:
  ai-pr-check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Block calls to segment.io
        shell: bash
        run: |
          grep -qxF '127.0.0.2 api.segment.io' /etc/hosts || echo '127.0.0.2 api.segment.io' | sudo tee -a /etc/hosts

      - name: Install macOS Docker Desktop dmg
        shell: bash
        run: |
          sw_vers
          mkdir ./temp
          mkdir ./mount

          buildUrl="https://desktop-stage.docker.com/mac/main/arm64/186043/Docker.dmg"

          sudo mkdir -p /Library/PrivilegedHelperTools
          curl --fail -o ./temp/DockerDesktop.dmg $buildUrl
          /usr/bin/hdiutil attach -noverify ./temp/DockerDesktop.dmg -mountpoint ./mount/desktop -nobrowse
          echo "dmg mounted"
          sudo ./mount/desktop/Docker.app/Contents/MacOS/install --accept-license --user runner
          echo "dmg installed"

          echo "ls /Library/Application Support/com.docker.docker"
          ls "/Library/Application Support/com.docker.docker" || true
          mkdir -p ./cache/desktopInstallSettings
          cp "/Library/Application Support/com.docker.docker/"* ./cache/desktopInstallSettings/
          echo "ls ./cache/desktopInstallSettings/"
          ls ./cache/desktopInstallSettings/ || true

          /usr/bin/hdiutil detach ./mount/desktop
          echo "dmg unmounted"

      - name: Install macOS Docker Desktop app
        shell: bash
        run: |
          /usr/bin/open /Applications/Docker.app --args --unattended --telemetry
          echo "Docker starting..."

      - name: Wait for Docker to be up and running
        shell: bash
        run: |
          until docker ps; do echo "docker not ready, sleep 10 s and try again"; sleep 10; done
          echo "Docker started and ready"
          docker version

      - name: Pull AI Model
        shell: bash
        run: |
          docker model pull ignaciolopezluna020/llama3.2-1b

      - name: Validate PR Description
        env:
          PR_DESCRIPTION: ${{ github.event.pull_request.body }}
        shell: bash
        run: |
          docker model run ignaciolopezluna020/llama3.2-1b "Review this PR description for clarity and completeness based on these guidelines:
          1. Clearly state the change implemented.
          2. Include issue numbers if relevant.
          3. Explicitly state any breaking changes.

          PR Description:
          \"$PR_DESCRIPTION\""
